### ISSUE TITLE
bed level

### ISSUE THREAD

**Issue by sigma1designer** [3DP-Tech/Ender-3-Max#4]
Dear sir,
Thank you so much for sharing the ender 3 max cr-touch firmware, the firmware is way more advanced, and I really loved it.
There is an issue with **16points bed leveling**, I had already read your point stating that using 310mm X 310 mm gives better leveling
but for the **last four points** on using 310mm on Y-axis the **bed's bottom is hitting the timing belt** of y axis this may reduce the life of belt and the nozzle is away from the bed on the 13th point.
Thanking you sir,

**Comment by porrey** [comment]
I am not having the issue. Can you send a a video showing what is happening? If you are comfortable compiling I can show you what setting to tweak.

**Comment by sigma1designer** [comment]
Sir, thank you for responding
here is the video link https://drive.google.com/file/d/1EkFpiPiHNoXmP-AEzYEynmqOMuRZFVH6/view?usp=share_link
I have pointed the contact of bed and belt with my finger please have a look at it, changing the y axis value to 300 or 305mm.
may solve the issue. One more issue is the info screen is jumping to options randomly, how often it's happening I haven't noticed but it's happening with a beep sound. this issue already exists in previous firmware but in this it's happening a bit more frequent, but it's not a big issue.
 other than these two the firmware is amazing.
I had lost my touch in coding long ago, if you could compile and save it in the profile it will help others like me or you can just tell what values to change, I will try it again myself.

**Comment by porrey** [comment]
I will work on a version with 305x305 and test it.

**Comment by sigma1designer** [comment]
Thank you, sir,
in the current firmware on 14th and 16th points of bed leveling the nozzle is right beside of the steel clips
hope new coordinates won't interfere with clips.
Rest of the firmware is amazing the bed adhesion is quite good, I stopped using glue stick, both abs and pla prints great

**Comment by porrey** [comment]
Here is a binary. 
[https://github.com/3DP-Tech/Ender-3-Max/raw/main/bin/305x305/firmware-20221212-204406.bin](url)

I changed three settings:

```
X_BED_SIZE 310 to 305
Y_BED_SIZE 310 to 305
PROBING_MARGIN 10 to 15
```

Looking at the original configuration, I remembered that `X_MIN_POS` and `Y_MIN_POS` are 0. These should have been -5 to center the printable area. This is another reason I changed to area to 310 by 310.

Please note I did not have time to fully test this. When you load it, run some simple movement tests before running a bed level. Also, move the print head to each corner and let me know if printable area is centered or not.

With the beds shrunk to 305 I may not have needed to increase the margin. If the margin needs to be changed back to 10 let me know.

If I find time during the week I will test these changes on my printer.

**Comment by sigma1designer** [comment]
Dear sir,
Thank you for your time,
here is my **cults3d profile**  https://cults3d.com/en/users/Culty_cute/creations
you can have any or all models at free of cost at any point of time, I will add new models every week. You can also contact me if you want any custom cad model will do it at free of cost, this is my mail i.d  sigma1designers@gmail.com
have a nice day

**Comment by sigma1designer** [comment]
Sir, I have just tested the firmware, as I mentioned my doubt earlier, the nozzle is hitting the clip at 14th point and the bed leveling halts without moving to the next point and on the 13th point the nozzle is at very much at the round edge and on the Y=0 coordinate the bottom bed is just touching the belt. Using 300 X 300 may fix the issue.

**Comment by porrey** [comment]
Here is the 300 by 300 with X and Y offsets:

https://github.com/3DP-Tech/Ender-3-Max/raw/main/bin/300x300/firmware-20221213-052531.bin

These are the changes made:
#define X_BED_SIZE 300
#define Y_BED_SIZE 300
#define X_MIN_POS -5
#define Y_MIN_POS -5

Let me know if this works or not.

**Comment by sigma1designer** [comment]
Dear sir, here is the video link for what's happening
https://drive.google.com/file/d/1iN9wA7rgTsknOoRsjWSpI4kswxbT15or/view?usp=share_link
the issue remains same as before I think minimum position needs to be 0.
on 14th point the nozzle is hitting the clip and pushed the bed so hard that my hand automatically went to the power switch, the bed's bottom is still hitting the belt.

**Comment by porrey** [comment]
Here is the 300 x 300 at X and Y minimums at 0. This is the default configuration for the Ender Max.

https://github.com/3DP-Tech/Ender-3-Max/raw/main/bin/300x300-0/firmware-20221213-060632.bin

**Comment by sigma1designer** [comment]
Thank you so much sir for your patience and time. Please do contact me if you need any custom cad model or models in my profile at any point of time
https://cults3d.com/en/users/Culty_cute/creations
my mail i.d sigma1designers@gmail.com
have a good day
