### ISSUE TITLE
Question: Difference between the binaries

### ISSUE THREAD

**Issue by sajacy** [3DP-Tech/Ender-3-Max#6]
In the bin folder, you have 300x300 and 300x300-0 more recently added.  I have the exact same mainboard with A/C marked for the drivers, and with CRTouch mounted on the OEM holes (barely not touching the blower fan!) I've changed the fans to Noctuas and have an Ender 3 Pro dual-z kit and a separately purchased 500mm rod ready to go on next.  Could you provide any insight on what the differences are?  Any recommendations?

**Comment by porrey** [comment]
This thread explains why they exist: [Issue #4](https://github.com/3DP-Tech/Ender-3-Max/issues/4)

My main binary has the bed dimensions defined as 310x310. The other two are at 300x300 which is what the original firmware had defined. The -0 version is the original dimensions and offsets while the other one attempted to center the grid on the bed.

I recommend trying the 310x310 first. If you have issues with any axis then try the 300x300 versions.

When using dual z-motors, you may want to increase the Z motor current from 580 to 1000.

`#define Z_CURRENT       580`

to

`#define Z_CURRENT       1000`

This setting can be found in **Configuration_adv.h**.
