### ISSUE TITLE
Parking missing layer and power loss manual resume

### ISSUE THREAD

**Issue by sigma1designer** [3DP-Tech/Ender-3-Max#7]
Dear sir,
                1. The firmware has layer missing issue with- pause, filament change, filament runout, power outage.
after the hot end returns to print from parking it's missing a layer.
 
For testing this I have used a 1cm cylinder stl, I have made post processing code to pause/ filament change at 5mm, after returning from parking it's having offset of next layer. 

               2. In creality 2.0.6 version the power loss has auto resume function but, in this version, when the power is back it's asking 'click to resume'.
               
               If you can solve or tell what changes need to be done, I'll do them.
I tried to solve the issue but didn't succeed. I tried the new 2.1.2 version but facing same issues.
here I have attached the image, stl file and video link.

image:
![IMG_20230304_232018](https://user-images.githubusercontent.com/120028094/222921678-ecb8c364-3820-4c03-8073-3805407a66c2.jpg)

stl file:
https://drive.google.com/file/d/1DI28znzfsdn5mIiFvoEDaLGu6kcIlPc8/view?usp=share_link

video link:
https://drive.google.com/file/d/1Hwk1OP7btvbP5aBaeO0OlfgNDg04MMIx/view?usp=share_link

Thank you.

**Comment by porrey** [comment]
I have checked the power loss settings against the base configuration on Marlin GitHub. There are no changes. If the configuration files from the original firmware are available, those settings can be compared to determine the necessary changes.

**Comment by sigma1designer** [comment]
I tried getting the config files from creality but they sent only compiled firmware, 
Thank you for your response.
Have a nice day.
